import { createRoot } from 'react-dom/client';
import Workspace from './app/workspace';
import { startPwa } from './lib/pwa';
import './app/globals.css';
import './app/reference-theme.css';
import './app/portal-theme.css';
import './app/red-accents.css';
import './app/training-theme.css';
import './app/auth-welcome.css';
import './app/interface-theme.css';
import './app/results-panel.css';
createRoot(document.getElementById('root')!).render(<Workspace />);
startPwa();
