import { useEffect, useState } from 'react';
import { createPortal } from 'react-dom';
import { Printer, RefreshCw } from 'lucide-react';
import { leadershipApi, type Attestation } from '@/lib/leadership-tools';
import { formatSiteDate } from '@/lib/date-time';
import './leadership-tools.css';
import './dashboard-print.css';
import TrainingProgress from './training-progress';
const statusNames = { preparing: 'Подготовка не завершена', pending: 'Заявка ожидает решения', approved: 'Допуск подтверждён', rejected: 'Возвращено на доработку', revoked: 'Допуск отозван', outdated: 'Требуется повторная подготовка' };
const readPerson = () => new URLSearchParams(window.location.hash.split('?')[1] || '').get('user') || '';
const score = (item: { score: number; total: number }) => (Math.round(item.score / item.total * 1000) / 10).toLocaleString('ru-RU') + '%';
const passed = (item: { score: number; total: number; passMark: number }) => item.score * 100 >= item.total * item.passMark;
export default function AttestationCard() {
  const [person, setPerson] = useState(readPerson);
  useEffect(() => { const update = () => setPerson(readPerson()); window.addEventListener('hashchange', update); return () => window.removeEventListener('hashchange', update); }, []);
  return <Card key={person} person={person}/>;
}
function Card({ person }: { person: string }) {
  const [data, setData] = useState<Attestation | null>(null), [loading, setLoading] = useState(true), [error, setError] = useState(''), [revision, setRevision] = useState(0);
  useEffect(() => { let active = true; setLoading(true); setData(null); setError('');
    leadershipApi<Attestation>('knowledge_attestation', person ? { userId: person } : {}).then(next => { if (active) setData(next); }).catch(cause => { if (active) setError(cause.message); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; };
  }, [person, revision]);
  return <section className="attestation" aria-labelledby="attestation-title"><header className="page-heading"><div><div className="eyebrow">ПОДГОТОВКА К СЛУЖБЕ</div><h1 id="attestation-title">Карточка аттестации</h1><p>{data?.person.displayName || 'Результаты проверок и актуальный допуск.'}</p></div><div className="dashboard-print-actions"><button type="button" className="button outline" disabled={loading} onClick={() => setRevision(n => n + 1)}><RefreshCw size={17}/>Обновить карточку</button><button type="button" className="button outline" disabled={loading || !data || !!error} onClick={() => window.print()}><Printer size={17}/>Печать / PDF</button></div></header>
    <p className="helper">Для PDF выберите «Сохранить как PDF» в окне печати.</p>{loading && <p role="status">Загружаем карточку…</p>}{error && <div className="error-banner" role="alert"><span>{error}</span><button type="button" className="button outline" onClick={() => setRevision(n => n + 1)}>Повторить</button></div>}
    {data && <><p className="helper">Сведения на {formatSiteDate(data.serverNow)}.</p><dl className="attestation-facts">{[['Статик',data.person.staticId || 'Не указан'],['Звание',data.person.rank || 'Не указано'],['Должность',data.person.position || 'Не указана'],['Состав',data.person.active ? 'Действующий сотрудник' : 'Вне действующего состава']].map(([label,value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>
      {data.clearance ? <section className={'attestation-clearance state-'+data.clearance.status}><h2>Текущий допуск</h2><h3>{statusNames[data.clearance.status]}</h3><p>Программа подготовки: редакция {data.clearance.programVersion}.</p><TrainingProgress materialsRead={data.clearance.materialsRead} materialCount={data.clearance.materialCount} testsPassed={data.clearance.requiredTestsPassed} testCount={data.clearance.requiredTestCount}/>{data.clearance.decidedAt && <p>Решение: {formatSiteDate(data.clearance.decidedAt)}{data.clearance.decidedBy && ' · ' + data.clearance.decidedBy}</p>}{data.clearance.note && <p className="attestation-note">{data.clearance.note}</p>}</section> : <p className="helper">Данные о допуске этого сотрудника доступны владельцу и заместителю.</p>}
      {data.results ? <><h2>Последние результаты по тестам <span className="count-pill">{data.results.length}</span></h2><p className="helper">Показана последняя завершённая проверка по каждому тесту. Обнуление назначения не удаляет результат. Тренировки и учебный пример исключены; текущий допуск рассчитывается отдельно.</p>{!data.results.length ? <p>Завершённых проверок пока нет.</p> : <ul className="attestation-results">{data.results.map(item => <li key={item.id}><h3>{item.title}</h3><div className="attestation-score"><strong>{score(item)}</strong><span className={'badge ' + (passed(item) ? 'green-badge' : 'orange-badge')}>{passed(item) ? 'Зачёт' : 'Без зачёта'}</span></div><p>{item.score} из {item.total} · проходной балл {item.passMark}% · {item.version === null ? 'Архивная редакция' : 'Редакция ' + item.version}<br/>{formatSiteDate(item.finishedAt)}</p></li>)}</ul>}</> : <p className="helper">Результаты этого сотрудника доступны от звания «Капитан».</p>}
      {createPortal(<article className="dashboard-print-root" aria-hidden="true"><header><p>УСБ ГИБДД · Россия Онлайн · Кутузовский</p><h1>Карточка аттестации</h1><p>Сформировано: {formatSiteDate(data.serverNow)}</p></header><h2>{data.person.displayName}</h2><table><tbody>{[['Статик',data.person.staticId || 'Не указан'],['Звание',data.person.rank || 'Не указано'],['Должность',data.person.position || 'Не указана'],['Состав',data.person.active ? 'Действующий сотрудник' : 'Вне действующего состава']].map(([label,value]) => <tr key={label}><th scope="row">{label}</th><td>{value}</td></tr>)}</tbody></table>
        {data.clearance && <><h2>Текущий допуск: {statusNames[data.clearance.status]}</h2><p>Программа: редакция {data.clearance.programVersion}. Материалы: {data.clearance.materialsRead} / {data.clearance.materialCount}. Обязательные тесты: {data.clearance.requiredTestsPassed} / {data.clearance.requiredTestCount}.</p>{data.clearance.decidedAt && <p>Решение: {formatSiteDate(data.clearance.decidedAt)}{data.clearance.decidedBy && ' · ' + data.clearance.decidedBy}</p>}{data.clearance.note && <p className="attestation-note">{data.clearance.note}</p>}</>}
        {data.results && <><h2>Последняя завершённая проверка по каждому тесту</h2><p>Проверок: {data.results.length}. Тренировки и учебный пример исключены.</p>{data.results.length > 0 && <table><thead><tr><th>Тест и редакция</th><th>Завершено, МСК</th><th>Результат</th></tr></thead><tbody>{data.results.map(item => <tr key={item.id}><td>{item.title}<br/>{item.version === null ? 'Архивная редакция' : 'Редакция ' + item.version}</td><td>{formatSiteDate(item.finishedAt)}</td><td>{item.score} / {item.total} · {score(item)}<br/>{passed(item) ? 'Зачёт' : 'Без зачёта'} · порог {item.passMark}%</td></tr>)}</tbody></table>}</>}
        <footer>Сведения на момент формирования. Обнуление назначения сохраняет результаты. Карточка содержит разделы, доступные пользователю; допуск рассчитывается по текущей программе отдельно от последней оценки.</footer>
      </article>, document.body)}
    </>}<p><a href="#history">Моя история</a> · <a href="#department?tab=staff">Состав подразделения</a></p>
  </section>;
}
