import { useEffect, useState } from 'react';
import { RefreshCw } from 'lucide-react';
import { leadershipApi, type ErrorAnalysis } from '@/lib/leadership-tools';
import { formatSiteDate } from '@/lib/date-time';
import './leadership-tools.css';
export default function ErrorAnalysisPanel() {
  const [days, setDays] = useState(30), [testId, setTestId] = useState(''), [revision, setRevision] = useState(0), [data, setData] = useState<ErrorAnalysis | null>(null), [loading, setLoading] = useState(true), [error, setError] = useState(''), [more, setMore] = useState(false);
  useEffect(() => { let active = true; setData(null); setError(''); setLoading(true);
    leadershipApi<ErrorAnalysis>('knowledge_analysis', { days, testId }).then(next => { if (active) setData(next); }).catch(cause => { if (active) setError(cause.message); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; };
  }, [days, testId, revision]);
  useEffect(() => { let active = true; if (!more || data?.nextOffset == null) return;
    leadershipApi<ErrorAnalysis>('knowledge_analysis', { days, testId, snapshot: data.snapshot, offset: data.nextOffset }).then(next => { if (active) setData(previous => previous && ({ ...next, questions: [...previous.questions, ...next.questions] })); }).catch(cause => { if (active) setError(cause.message); }).finally(() => { if (active) setMore(false); }); return () => { active = false; };
  }, [more, days, testId, revision]);
  const percent = (value: number | null) => value === null ? '—' : value.toLocaleString('ru-RU') + '%';
  return <section className="error-analysis" aria-labelledby="analysis-title"><header className="page-heading"><div><div className="eyebrow">ПОДГОТОВКА СОТРУДНИКОВ</div><h1 id="analysis-title">Анализ ошибок</h1><p>Темы для повторения и вопросы с наибольшей долей ошибок.</p></div><button type="button" className="button outline" disabled={loading || more} onClick={() => setRevision(n => n + 1)}><RefreshCw size={17}/>Обновить анализ</button></header>
    <div className="bulk-fields"><label className="field">Период анализа<select value={days} disabled={more} onChange={event => { setDays(Number(event.target.value)); setTestId(''); }}><option value={7}>7 дней</option><option value={30}>30 дней</option><option value={90}>90 дней</option></select></label><label className="field">Тест в анализе<select value={testId} disabled={loading || more} onChange={event => setTestId(event.target.value)}><option value="">Все тесты</option>{data?.tests.map(test => <option key={test.id} value={test.id}>{test.title}</option>)}</select></label></div>
    {loading && <p role="status">Считаем ошибки по завершённым проверкам…</p>}{error && <div className="error-banner" role="alert"><span>{error}</span><button type="button" className="button outline" disabled={more} onClick={() => { setError(''); data?.nextOffset != null ? setMore(true) : setRevision(n => n + 1); }}>Повторить</button></div>}
    {data && <><p className="helper">{data.period.from.split('-').reverse().join('.')} — {data.period.to.split('-').reverse().join('.')} · МСК. Данные: {formatSiteDate(data.snapshot)}. Учитываются все завершённые проверки, включая повторные попытки. Тренировки и учебный пример исключены.</p><div className="analysis-metrics"><article><span>Проверок</span><strong>{data.summary.exams}</strong></article><article><span>Ответов с ошибкой</span><strong>{data.summary.wrong} / {data.summary.seen}</strong><small>Без ответа: {data.summary.unanswered}</small></article><article><span>Доля ошибок</span><strong>{percent(data.summary.errorRate)}</strong></article></div>
      <h2>Темы для повторения</h2><p className="helper">Категории взяты из текущих карточек тестов. Пропущенный ответ считается ошибкой.</p>{!data.topics.length ? <p>За этот период завершённых проверок нет.</p> : <ul className="analysis-topics">{data.topics.map(topic => <li key={topic.name}><h3>{topic.name}</h3><strong>{percent(topic.errorRate)} ошибок</strong><p>{topic.wrong} из {topic.seen} ответов · проверок: {topic.exams} · без ответа: {topic.unanswered}</p></li>)}</ul>}
      <h2>Вопросы с ошибками <span className="count-pill">{data.totalQuestions}</span></h2><p className="helper">Редакции теста и изменённые вопросы считаются отдельно. Перемешивание ответов учитывается по сохранённой попытке.</p>{!data.questions.length ? <p>Ошибок за этот период не найдено.</p> : <ol className="analysis-questions">{data.questions.map(item => <li key={item.id}><p className="eyebrow">{item.testTitle} · {item.version === null ? 'Архивная редакция' : 'Редакция ' + item.version}</p><h3>{item.text}</h3><p><strong>{percent(item.errorRate)} ошибок</strong> · {item.wrong} из {item.seen} ответов · без ответа: {item.unanswered}</p></li>)}</ol>}
      {data.nextOffset != null && <button type="button" className="button outline" disabled={more} onClick={() => setMore(true)}>{more ? 'Загружаем…' : 'Показать ещё вопросы'}</button>}<p className="helper">Показано {data.questions.length} из {data.totalQuestions} вопросов с ошибками.</p>
    </>}
  </section>;
}
