import { useEffect, useState } from 'react';
import { RefreshCw } from 'lucide-react';
import { supportApi, type ContentReport } from '@/lib/support-api';
import { appealStatuses } from '@/lib/department-api';
import { formatSiteDate } from '@/lib/date-time';
import './site-improvements.css';
export default function FeedbackSection({ canManage }: { canManage: boolean }) {
  const [scope, setScope] = useState(canManage ? 'team' : 'mine'), [status, setStatus] = useState('all'), [offset, setOffset] = useState(0), [retry, setRetry] = useState(0);
  const [data, setData] = useState<{ total: number; items: ContentReport[] } | null>(null), [error, setError] = useState(''), [loading, setLoading] = useState(true);
  useEffect(() => { let active = true; setLoading(true); setError(''); setData(null); void supportApi<{ total: number; items: ContentReport[] }>({ action: 'list', scope: canManage ? scope : 'mine', status, offset }).then(next => { if (active) setData(next); }).catch(cause => { if (active) setError(cause.message); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [scope, status, offset, retry, canManage]);
  const refresh = () => setRetry(value => value + 1);
  return <div className="department-content"><h2>Сообщения об ошибках</h2><p className="portal-note">Неточности в вопросах и статьях, ответы руководства и статус исправления.</p><div className="support-toolbar">{canManage && <label className="field">Очередь<select value={scope} onChange={event => { setScope(event.target.value); setOffset(0); }}><option value="team">Все сообщения</option><option value="mine">Мои сообщения</option></select></label>}<label className="field">Статус<select value={status} onChange={event => { setStatus(event.target.value); setOffset(0); }}><option value="all">Все статусы</option>{Object.entries(appealStatuses).map(([key, value]) => <option key={key} value={key}>{value}</option>)}</select></label><button className="button outline" disabled={loading} onClick={refresh}><RefreshCw size={16}/>Обновить</button></div>
    {loading && <p role="status">Загружаем сообщения…</p>}{error && <p className="inline-error" role="alert">{error} <button className="text-button" onClick={refresh}>Повторить</button></p>}
    {data && <><p className="helper">Найдено: {data.total}</p><div className="feedback-list">{data.items.map(item => <Report key={item.id + ':' + item.version} item={item} canManage={canManage} onSaved={refresh}/>)}</div>{!data.items.length && <p>По выбранному фильтру сообщений пока нет. Используйте кнопку «Сообщить об ошибке» возле вопроса или статьи.</p>}{data.total > 20 && <div className="feedback-actions"><button className="button outline" disabled={offset === 0} onClick={() => setOffset(value => value - 20)}>Назад</button><span>{offset + 1}–{Math.min(offset + 20, data.total)} из {data.total}</span><button className="button outline" disabled={offset + 20 >= data.total} onClick={() => setOffset(value => value + 20)}>Далее</button></div>}</>}
  </div>;
}
function Report({ item, canManage, onSaved }: { item: ContentReport; canManage: boolean; onSaved: () => void }) {
  const [status, setStatus] = useState('in_review'), [response, setResponse] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const save = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { await supportApi({ action: 'review', id: item.id, version: item.version, status, response }); onSaved(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Не удалось сохранить ответ.'); } finally { setBusy(false); } };
  return <article className="feedback-card"><p className="feedback-status">№ {item.id.slice(0, 8).toUpperCase()} · {appealStatuses[item.status]} · {formatSiteDate(item.createdAt)}</p><h3>{item.kind === 'question' ? item.context.testTitle : 'Статья или пункт правил'}</h3>{item.context.text && <p className="feedback-context">{item.context.text}</p>}{item.context.testVersion != null && <p className="helper">Редакция теста: {item.context.testVersion}</p>}{item.kind === 'law' && <a href={item.context.document === 'state-organizations' ? '#new-employees?topic=project-rules' : `#laws?document=${item.context.document}&article=${item.context.article}`}>Открыть материал →</a>}<p className="department-preserve">{item.description}</p><p className="helper">Отправил: {item.authorLogin}</p>{item.response && <div className="appeal-response"><h4>Ответ руководства</h4><p className="department-preserve">{item.response}</p></div>}
    {canManage && <details><summary>Изменить статус и ответить</summary><form className="portal-form" onSubmit={save}><label className="field">Статус<select value={status} onChange={event => setStatus(event.target.value)}>{Object.entries(appealStatuses).filter(([key]) => key !== 'new').map(([key, value]) => <option key={key} value={key}>{value}</option>)}</select></label><label className="field">Ответ<textarea rows={3} maxLength={4000} required={status !== 'in_review'} minLength={status !== 'in_review' ? 10 : undefined} value={response} onChange={event => setResponse(event.target.value)}/></label>{error && <p role="alert" className="inline-error">{error}</p>}<button className="button primary" disabled={busy}>Сохранить ответ</button></form></details>}
  </article>;
}
