import {useEffect,useRef,useState} from 'react';
import {Camera,Plus,Loader2,Pencil} from 'lucide-react';
import {toast} from 'sonner';
import {photoUrls,inspectPhoto,uploadPhoto,serviceApi,type Photo} from '@/lib/service-api';
import {errorMessage} from '@/lib/department-api';
import {useServiceData} from './use-service-data';
import {ServiceHeading,ServiceLoad,ServiceDialog,ServiceRefresh,ServicePagination,ServiceFormError} from './service-ui';
type Draft={id:string;title:string;caption:string;version:number;file:File|null;existing:boolean};
export default function GalleryManagement() {
 const [offset,setOffset]=useState(0),{data,loading,error,refresh}=useServiceData<{items:Photo[];total:number}>({action:'photos',manage:true,offset});
 const [images,setImages]=useState<Photo[]>([]),[imageError,setImageError]=useState(''),[draft,setDraft]=useState<Draft|null>(null),[busy,setBusy]=useState(false),[formError,setFormError]=useState(''),[preview,setPreview]=useState('');const selection=useRef(0);
 useEffect(()=>{let active=true;setImages([]);setImageError('');if(data)void photoUrls(data.items).then(items=>{if(active)setImages(items);}).catch(e=>{if(active){setImages(data.items);setImageError(errorMessage(e));}});return()=>{active=false;};},[data]);
 useEffect(()=>{if(!draft?.file){setPreview('');return;}const url=URL.createObjectURL(draft.file);setPreview(url);return()=>URL.revokeObjectURL(url);},[draft?.file]);
 const changed=()=>{refresh();window.dispatchEvent(new Event('usb-gallery-changed'));};
 const edit=(photo?:Photo)=>{selection.current++;setFormError('');setDraft(photo?{id:photo.id,title:photo.title,caption:photo.caption,version:photo.version,file:null,existing:true}:{id:crypto.randomUUID(),title:'',caption:'',version:0,file:null,existing:false});};
 const choose=async(file?:File)=>{if(!file||!draft)return;const token=++selection.current;setFormError('');setDraft(value=>value?{...value,file:null}:null);try{await inspectPhoto(file);if(token===selection.current)setDraft(value=>value?{...value,id:crypto.randomUUID(),file}:null);}catch(e){if(token===selection.current)setFormError(errorMessage(e));}};
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(!draft||busy)return;setBusy(true);setFormError('');try{if(draft.existing)await serviceApi({action:'photoSave',id:draft.id,version:draft.version,title:draft.title,caption:draft.caption});else{if(!draft.file)throw new Error('Выберите изображение.');await uploadPhoto(draft.file,draft.id,draft.title,draft.caption);}setDraft(null);changed();toast.success('Фото опубликовано в галерее');}catch(cause){setFormError(errorMessage(cause));}finally{setBusy(false);}};
 const archive=async(photo:Photo)=>{setBusy(true);setFormError('');try{await serviceApi({action:'photoArchive',id:photo.id,version:photo.version});changed();toast.success('Фото снято с публикации');}catch(e){setFormError(errorMessage(e));}finally{setBusy(false);}};
 return <div className="service-tools"><ServiceHeading title="Фотогалерея" description="Добавляйте игровые скриншоты и подписи. Опубликованные фотографии видны всем посетителям сайта." actions={<><ServiceRefresh refresh={refresh} busy={busy}/><button type="button" className="button primary" disabled={busy} onClick={()=>edit()}><Plus size={17}/>Загрузить фото</button></>}/><p className="portal-note">JPEG, PNG или WebP · до 5 МБ. Исходное изображение сохраняется без обрезки.</p><ServiceLoad loading={loading} error={error} refresh={refresh}/><ServiceFormError message={imageError||(!draft?formError:'')}/>
  {!loading&&!error&&<><div className="service-photo-grid">{images.map(photo=><article className="department-card service-photo" key={photo.id}>{photo.url?<a href={photo.url} target="_blank" rel="noopener noreferrer"><img src={photo.url} alt={photo.title} width={photo.width} height={photo.height}/></a>:<div className="service-photo-missing"><Camera size={30}/>Загрузка не завершена</div>}<div><span className="badge">{{draft:'Черновик',published:'Опубликовано',archived:'Снято с публикации'}[photo.status]}</span><h3>{photo.title}</h3>{photo.caption&&<p>{photo.caption}</p>}<div className="portal-actions"><button type="button" className="button outline" disabled={busy} onClick={()=>edit(photo)}><Pencil size={15}/>{photo.status==='published'?'Изменить подпись':'Опубликовать'}</button>{photo.status!=='archived'&&<button type="button" className="text-button" disabled={busy} onClick={()=>void archive(photo)}>Снять с публикации</button>}</div></div></article>)}</div>{!data?.items.length&&<div className="department-empty"><Camera size={30}/><h3>Добавленных фотографий пока нет</h3><p>Официальные кадры остаются в галерее главной страницы. Здесь можно добавить фотографии вашей службы.</p></div>}<ServicePagination offset={offset} total={data?.total||0} onChange={setOffset}/></>}
  {draft&&<ServiceDialog title={draft.existing?'Подпись и публикация':'Загрузить фотографию'} description="После публикации фото появится в галерее на главной странице." busy={busy} onClose={()=>{selection.current++;setDraft(null);}}><form className="portal-form" onSubmit={save}>{!draft.existing&&<label className="field">Изображение<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>void choose(e.target.files?.[0])}/></label>}{preview&&<img className="service-upload-preview" src={preview} alt="Выбранная фотография"/>}<label className="field">Подпись<input required minLength={3} maxLength={140} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label className="field">Описание<textarea aria-label="Описание" rows={3} maxLength={1500} value={draft.caption} onChange={e=>setDraft({...draft,caption:e.target.value})}/></label><ServiceFormError message={formError}/><div className="portal-actions"><button type="button" className="button outline" disabled={busy} onClick={()=>{selection.current++;setDraft(null);}}>Отмена</button><button className="button primary" disabled={busy||(!draft.existing&&!draft.file)}>{busy&&<Loader2 size={17} className="spin"/>}Опубликовать фото</button></div></form></ServiceDialog>}
 </div>;
}
