import {useRef,useState} from 'react';
import {MapPin,Plus,Minus,Route,Trash2,Pencil,Save} from 'lucide-react';
import {toast} from 'sonner';
import {serviceApi,type ServiceMapData,type Point,type MapPin as Pin,type MapRoute} from '@/lib/service-api';
import {errorMessage} from '@/lib/department-api';
import {useServiceData} from './use-service-data';
import {ServiceHeading,ServiceLoad,ServiceRefresh,ServiceFormError} from './service-ui';
type Draft={id:string;title:string;description:string;kind:'post'|'object'|'route';points:Point[]};
const bound=(value:number,size:number)=>Math.max(0,Math.min(1000-size,value));
export default function ServiceMap({canManage}:{canManage:boolean}) {
 const {data,loading,error,refresh}=useServiceData<ServiceMapData>({action:'map'});
 const [view,setView]=useState({x:0,y:0,size:1000}),[selected,setSelected]=useState(''),[draft,setDraft]=useState<Draft|null>(null),[busy,setBusy]=useState(false),[issue,setIssue]=useState('');
 const svg=useRef<SVGSVGElement|null>(null),drag=useRef<{x:number;y:number;view:typeof view;moved:boolean}|null>(null);
 const zoom=(factor:number)=>setView(v=>{const size=Math.max(150,Math.min(1000,v.size*factor));return {size,x:bound(v.x+(v.size-size)/2,size),y:bound(v.y+(v.size-size)/2,size)};});
 const items=[...(data?.pins||[]),...(data?.routes||[])],chosen=items.find(item=>item.id===selected);
 const choose=(item:Pin|MapRoute)=>{setSelected(item.id);const point='points' in item?item.points[0]:item;setView(v=>({...v,x:bound(point.x-v.size/2,v.size),y:bound(point.y-v.size/2,v.size)}));};
 const edit=(item?:Pin|MapRoute)=>{setIssue('');setDraft(item?{id:item.id,title:item.title,description:item.description||'',kind:item.kind,points:'points' in item?[...item.points]:[{x:item.x,y:item.y}]}:{id:crypto.randomUUID(),title:'',description:'',kind:'post',points:[]});};
 const persist=async(pins:Pin[],routes:MapRoute[])=>{if(!data||busy)return;setBusy(true);setIssue('');try{await serviceApi({action:'mapSave',version:data.version,pins,routes});setDraft(null);refresh();toast.success('Карта службы сохранена');}catch(e){setIssue(errorMessage(e));}finally{setBusy(false);}};
 const save=(e:React.FormEvent)=>{e.preventDefault();if(!draft||!data)return;const pins=data.pins.filter(p=>p.id!==draft.id),routes=data.routes.filter(r=>r.id!==draft.id);
  if(draft.kind==='route'){if(draft.points.length<2)return;routes.push({id:draft.id,title:draft.title,description:draft.description,kind:'route',points:draft.points});}
  else {if(!draft.points.length)return;pins.push({id:draft.id,title:draft.title,description:draft.description,kind:draft.kind,...draft.points[0]});}void persist(pins,routes);
 };
 const up=(e:React.PointerEvent<SVGSVGElement>)=>{const prior=drag.current;drag.current=null;if(!prior||prior.moved||!draft||busy||!svg.current)return;const pt=svg.current.createSVGPoint();pt.x=e.clientX;pt.y=e.clientY;const matrix=svg.current.getScreenCTM();if(!matrix)return;const point=pt.matrixTransform(matrix.inverse());const p={x:Math.max(0,Math.min(1000,point.x)),y:Math.max(0,Math.min(1000,point.y))};setDraft(value=>value?{...value,points:value.kind==='route'?[...value.points,p].slice(0,50):[p]}:null);};
 return <div className="service-tools"><ServiceHeading title="Карта службы" description="Посты, важные объекты и маршруты патрулирования на карте игровой Москвы." actions={<><ServiceRefresh refresh={refresh} busy={busy}/>{canManage&&<button type="button" className="button primary" disabled={busy||loading} onClick={()=>edit()}><Plus size={17}/>Добавить на карту</button>}</>}/><ServiceLoad loading={loading} error={error} refresh={refresh}/><ServiceFormError message={issue}/>{data&&!loading&&!error&&<><div className="service-map-layout"><div><div className="service-map-controls"><button type="button" className="button outline" aria-label="Приблизить карту" onClick={()=>zoom(.7)}><Plus size={18}/></button><button type="button" className="button outline" aria-label="Отдалить карту" onClick={()=>zoom(1.4)}><Minus size={18}/></button><button type="button" className="button outline" onClick={()=>setView({x:0,y:0,size:1000})}>Вся карта</button><span>Перетаскивайте карту для перемещения</span></div><svg ref={svg} className={'service-map-canvas'+(draft?' is-drawing':'')} viewBox={`${view.x} ${view.y} ${view.size} ${view.size}`} aria-label="Интерактивная карта Москвы в России Онлайн" role="group" tabIndex={0} onKeyDown={e=>{if(e.target!==e.currentTarget)return;const step=view.size*.1;const dx=e.key==='ArrowLeft'?-step:e.key==='ArrowRight'?step:0,dy=e.key==='ArrowUp'?-step:e.key==='ArrowDown'?step:0;if(dx||dy){e.preventDefault();setView(v=>({...v,x:bound(v.x+dx,v.size),y:bound(v.y+dy,v.size)}));}}} onPointerDown={e=>{if((e.target as Element).closest('[data-map-pin]'))return;drag.current={x:e.clientX,y:e.clientY,view:{...view},moved:false};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{const d=drag.current;if(!d)return;const dx=e.clientX-d.x,dy=e.clientY-d.y;if(Math.abs(dx)+Math.abs(dy)<5)return;d.moved=true;const rect=e.currentTarget.getBoundingClientRect();setView({...d.view,x:bound(d.view.x-dx/rect.width*d.view.size,d.view.size),y:bound(d.view.y-dy/rect.height*d.view.size,d.view.size)});}} onPointerUp={up} onPointerCancel={()=>{drag.current=null;}}>
   <image href={`${import.meta.env.BASE_URL}map/moscow.svg`} width="1000" height="1000"/>{data.routes.map(route=><polyline key={route.id} points={route.points.map(p=>`${p.x},${p.y}`).join(' ')} fill="none" stroke={selected===route.id?'#ffb5c7':'#da758f'} strokeWidth={view.size*.006} strokeLinecap="round" strokeLinejoin="round"><title>{route.title}</title></polyline>)}{data.pins.map(pin=><g data-map-pin key={pin.id} role="button" tabIndex={0} aria-label={pin.title} onClick={()=>choose(pin)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose(pin);}}}><circle cx={pin.x} cy={pin.y} r={view.size*.013} fill={pin.kind==='post'?'#69bddc':'#e9bd76'} stroke={selected===pin.id?'#fff':'#17202b'} strokeWidth={view.size*.004}/><title>{pin.title}</title></g>)}{draft&&<>{draft.kind==='route'&&<polyline points={draft.points.map(p=>`${p.x},${p.y}`).join(' ')} fill="none" stroke="#fff" strokeDasharray="8 5" strokeWidth={view.size*.005}/>} {draft.points.map((p,i)=><circle key={i} cx={p.x} cy={p.y} r={view.size*.01} fill="#fff" stroke="#d56483" strokeWidth={view.size*.003}/>)}</>}
  </svg><p className="service-map-source">Основа карты: <a href="https://wiki.russia.online/ru/map" target="_blank" rel="noopener noreferrer">официальная вики «России Онлайн» ↗</a></p><div className="service-map-legend"><span><i className="post"/>Пост</span><span><i className="object"/>Объект</span><span><i className="route"/>Маршрут</span></div></div><aside className="service-map-list"><h3>Метки и маршруты</h3>{!items.length&&<p>Метки ещё не добавлены. Руководство может отметить посты и нарисовать маршруты на карте.</p>}{items.map(item=><button type="button" className="service-map-item" aria-pressed={item.id===selected} key={item.id} onClick={()=>choose(item)}>{item.kind==='route'?<Route size={17}/>:<MapPin size={17}/>}<span>{item.title}<small>{{post:'Пост',object:'Объект',route:'Маршрут'}[item.kind]}</small></span></button>)}{chosen&&<div className="service-map-detail"><h4>{chosen.title}</h4><p>{chosen.description}</p>{canManage&&<div className="portal-actions"><button type="button" className="button outline" disabled={busy} onClick={()=>edit(chosen)}><Pencil size={15}/>Изменить</button><button type="button" className="text-button" disabled={busy} onClick={()=>void persist(data.pins.filter(p=>p.id!==chosen.id),data.routes.filter(r=>r.id!==chosen.id))}><Trash2 size={15}/>Удалить</button></div>}</div>}</aside></div>
  {draft&&<form className="department-card service-map-form portal-form" onSubmit={save}><h3>{items.some(item=>item.id===draft.id)?'Изменить метку или маршрут':'Добавить на карту'}</h3><div className="portal-form-row"><label className="field">Название<input required minLength={3} maxLength={100} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label className="field">Тип<select aria-label="Тип" value={draft.kind} onChange={e=>setDraft({...draft,kind:e.target.value as Draft['kind'],points:[]})}><option value="post">Пост</option><option value="object">Объект</option><option value="route">Маршрут</option></select></label></div><label className="field">Описание<textarea aria-label="Описание" rows={2} maxLength={1000} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><p role="status">{draft.kind==='route'?`Нажмите на карте последовательно для построения маршрута. Точек: ${draft.points.length} из 50.`:draft.points.length?'Положение выбрано. Нажмите на карте, чтобы изменить его.':'Нажмите на карте, чтобы выбрать положение метки.'}</p><div className="portal-actions"><button type="button" className="button outline" disabled={busy} onClick={()=>setDraft(null)}>Отмена</button>{draft.points.length>0&&<button type="button" className="button outline" disabled={busy} onClick={()=>setDraft({...draft,points:draft.points.slice(0,-1)})}>Убрать последнюю точку</button>}<button className="button primary" disabled={busy||draft.points.length<(draft.kind==='route'?2:1)}><Save size={17}/>Сохранить на карте</button></div></form>}</>}
 </div>;
}
