import {useState} from 'react';
import {CalendarDays,Plus,ChevronLeft,ChevronRight,Loader2,UserPlus} from 'lucide-react';
import {toast} from 'sonner';
import {serviceApi,type ServiceContext,type ServiceShift,type Replacement,type ShiftPage} from '@/lib/service-api';
import {errorMessage} from '@/lib/department-api';
import {formatSiteDate,fromSiteDateTimeInput,toSiteDateTimeInput} from '@/lib/date-time';
import {useServiceData} from './use-service-data';
import {ServiceHeading,ServiceLoad,ServiceRefresh,ServiceDialog,ServiceFormError,MemberSelect} from './service-ui';
type ShiftDraft={id:string;version:number;title:string;location:string;startsAt:string;endsAt:string;capacity:number};
const today=()=>toSiteDateTimeInput(Date.now()).slice(0,10);
const addDays=(day:string,n:number)=>new Date(Date.parse(day+'T12:00:00Z')+n*86400000).toISOString().slice(0,10);
const states={pending:'Ожидает решения',accepted:'Замена согласована',rejected:'Отклонена'};
export default function ServiceShifts({context}:{context:ServiceContext}) {
 const [day,setDay]=useState(today),[busy,setBusy]=useState(false),[issue,setIssue]=useState('');
 const {data,loading,error,refresh}=useServiceData<ShiftPage>({action:'shifts',from:fromSiteDateTimeInput(day+'T00:00'),to:fromSiteDateTimeInput(addDays(day,7)+'T00:00')});
 const [draft,setDraft]=useState<ShiftDraft|null>(null),[replacement,setReplacement]=useState<ServiceShift|null>(null),[reason,setReason]=useState(''),[assign,setAssign]=useState<ServiceShift|null>(null),[userId,setUserId]=useState(''),[review,setReview]=useState<Replacement|null>(null),[decision,setDecision]=useState('accepted'),[response,setResponse]=useState('');
 const run=async(payload:Record<string,unknown>,success:string)=>{if(busy)return;setBusy(true);setIssue('');try{await serviceApi(payload);setDraft(null);setReplacement(null);setAssign(null);setReview(null);if(payload.action==='shiftSave')setDay(toSiteDateTimeInput(String(payload.startsAt)).slice(0,10));refresh();toast.success(success);}catch(cause){setIssue(errorMessage(cause));}finally{setBusy(false);}};
 const edit=(shift?:ServiceShift)=>{setIssue('');const starts=Math.max(Date.now()+3600000,Date.parse(fromSiteDateTimeInput(day+'T10:00')));setDraft(shift?{id:shift.id,version:shift.version,title:shift.title,location:shift.location,startsAt:toSiteDateTimeInput(shift.starts_at),endsAt:toSiteDateTimeInput(shift.ends_at),capacity:shift.capacity}:{id:crypto.randomUUID(),version:0,title:'',location:'',startsAt:toSiteDateTimeInput(starts),endsAt:toSiteDateTimeInput(starts+7200000),capacity:2});};
 const save=(e:React.FormEvent)=>{e.preventDefault();if(!draft)return;try{void run({action:'shiftSave',...draft,startsAt:fromSiteDateTimeInput(draft.startsAt),endsAt:fromSiteDateTimeInput(draft.endsAt)},'Смена сохранена');}catch(cause){setIssue(errorMessage(cause));}};
 const modal=!!(draft||replacement||assign||review);
 return <div className="service-tools"><ServiceHeading title="График дежурств" description="Записывайтесь на смены, смотрите состав патруля и согласовывайте замену. Время указано по МСК." actions={<><ServiceRefresh refresh={refresh} busy={busy}/>{context.canManage&&<button type="button" className="button primary" disabled={busy} onClick={()=>edit()}><Plus size={17}/>Создать смену</button>}</>}/>
 <div className="service-week-controls"><button type="button" className="button outline" aria-label="Предыдущие семь дней" onClick={()=>setDay(addDays(day,-7))}><ChevronLeft size={18}/></button><label className="field">Начало периода<input type="date" required value={day} onChange={e=>{if(/^\d{4}-\d{2}-\d{2}$/.test(e.target.value))setDay(e.target.value);}}/></label><button type="button" className="button outline" aria-label="Следующие семь дней" onClick={()=>setDay(addDays(day,7))}><ChevronRight size={18}/></button><button type="button" className="text-button" onClick={()=>setDay(today())}>Сегодня</button></div>
 <ServiceLoad loading={loading} error={error} refresh={refresh}/>{!modal&&<ServiceFormError message={issue}/>}
 {data&&!loading&&!error&&<><div className="service-shift-list">{data.items.map(shift=>{const own=shift.members.some(m=>m.id===context.userId),past=Date.parse(shift.starts_at)<=Date.now(),closed=shift.cancelled||past,pending=data.requests.some(r=>r.shift_id===shift.id&&r.requester_id===context.userId&&r.status==='pending');return <article key={shift.id} className={'department-card service-shift'+(closed?' is-closed':'')}><div className="portal-heading"><h3>{shift.title}</h3><span className="badge">{shift.cancelled?'Отменена':past?'Началась или завершена':`${shift.members.length} из ${shift.capacity} мест`}</span></div><p className="service-shift-date"><CalendarDays size={17}/>{formatSiteDate(shift.starts_at)} — {formatSiteDate(shift.ends_at)}</p><p>Место службы: {shift.location}</p><div className="service-shift-members"><strong>Состав патруля</strong>{shift.members.length?<ul>{shift.members.map(m=><li key={m.id}>{m.name}{m.id===context.userId?' · вы':''}</li>)}</ul>:<p>На смену пока никто не записался.</p>}</div>{!closed&&<div className="portal-actions">{own?<><button type="button" className="button outline" disabled={busy||pending} onClick={()=>{setIssue('');setReason('');setReplacement(shift);}}>{pending?'Замена на рассмотрении':'Запросить замену'}</button><button type="button" className="text-button" disabled={busy} onClick={()=>void run({action:'shiftLeave',id:shift.id},'Запись на смену отменена')}>Отменить мою запись</button></>:<button type="button" className="button primary" disabled={busy||shift.members.length>=shift.capacity} onClick={()=>void run({action:'shiftJoin',id:shift.id},'Вы записаны на смену')}><UserPlus size={16}/>Записаться</button>}{context.canManage&&<><button type="button" className="button outline" disabled={busy||shift.members.length>=shift.capacity} onClick={()=>{setIssue('');setUserId('');setAssign(shift);}}>Назначить сотрудника</button>{!shift.members.length&&<button type="button" className="text-button" disabled={busy} onClick={()=>edit(shift)}>Изменить смену</button>}<button type="button" className="text-button" disabled={busy} onClick={()=>void run({action:'shiftCancel',id:shift.id,version:shift.version},'Смена отменена')}>Отменить смену</button></>}</div>}</article>;})}</div>{!data.items.length&&<div className="department-empty"><CalendarDays size={30}/><h3>На эти семь дней смен пока нет</h3><p>{context.canManage?'Создайте смену, укажите время, место и число сотрудников.':'Дежурства появятся после публикации руководством.'}</p></div>}
 {data.requests.length>0&&<section className="service-replacements"><h3>{context.canManage?'Заявки на замену':'Мои заявки на замену'}</h3>{data.requests.map(item=><article className="department-card service-replacement" key={item.id}><span className="badge">{states[item.status]}</span><h4>{item.shiftTitle}</h4><p>{item.requesterName} · {formatSiteDate(item.startsAt)}</p><p className="service-body">{item.reason}</p>{item.response&&<p className="service-body">Ответ руководства: {item.response}</p>}{item.replacement_id&&<p>Замена: {context.members.find(m=>m.id===item.replacement_id)?.name||'Назначенный сотрудник'}</p>}{context.canManage&&item.status==='pending'&&<button type="button" className="button outline" disabled={busy} onClick={()=>{setIssue('');setUserId('');setResponse('');setDecision('accepted');setReview(item);}}>Рассмотреть замену</button>}</article>)}</section>}</>}
 {draft&&<ServiceDialog title={draft.version?'Изменить смену':'Новая смена'} description="Смена длится до 24 часов. После записи сотрудников время и место можно изменить только через отмену и создание новой смены." busy={busy} onClose={()=>setDraft(null)}><form className="portal-form" onSubmit={save}><label className="field">Название смены<input required minLength={3} maxLength={140} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label className="field">Место службы<input required minLength={3} maxLength={160} value={draft.location} onChange={e=>setDraft({...draft,location:e.target.value})}/></label><div className="portal-form-row"><label className="field">Начало по МСК<input required type="datetime-local" value={draft.startsAt} onChange={e=>setDraft({...draft,startsAt:e.target.value})}/></label><label className="field">Окончание по МСК<input required type="datetime-local" value={draft.endsAt} onChange={e=>setDraft({...draft,endsAt:e.target.value})}/></label></div><label className="field">Число сотрудников<input required type="number" min={1} max={10} value={draft.capacity} onChange={e=>setDraft({...draft,capacity:Number(e.target.value)})}/></label><ServiceFormError message={issue}/><button className="button primary" disabled={busy}>{busy&&<Loader2 size={17} className="spin"/>}Сохранить смену</button></form></ServiceDialog>}
 {replacement&&<ServiceDialog title="Запросить замену" description="Вы остаётесь в составе смены до согласования замены руководством." busy={busy} onClose={()=>setReplacement(null)}><form className="portal-form" onSubmit={e=>{e.preventDefault();void run({action:'replacement',id:replacement.id,reason},'Заявка на замену отправлена');}}><p>{replacement.title} · {formatSiteDate(replacement.starts_at)}</p><label className="field">Причина замены<textarea aria-label="Причина замены" required minLength={10} maxLength={2000} rows={3} value={reason} onChange={e=>setReason(e.target.value)}/></label><ServiceFormError message={issue}/><button className="button primary" disabled={busy}>Отправить заявку</button></form></ServiceDialog>}
 {assign&&<ServiceDialog title="Назначить сотрудника" description="Система проверит свободные места и другие смены выбранного сотрудника." busy={busy} onClose={()=>setAssign(null)}><form className="portal-form" onSubmit={e=>{e.preventDefault();void run({action:'shiftAssign',id:assign.id,userId},'Сотрудник назначен на смену');}}><p>{assign.title}</p><MemberSelect members={context.members.filter(m=>!assign.members.some(p=>p.id===m.id))} value={userId} onChange={setUserId}/><ServiceFormError message={issue}/><button className="button primary" disabled={busy}>Назначить на смену</button></form></ServiceDialog>}
 {review&&<ServiceDialog title="Рассмотреть замену" description="При согласовании система заменит сотрудника в составе смены." busy={busy} onClose={()=>setReview(null)}><form className="portal-form" onSubmit={e=>{e.preventDefault();void run({action:'replacementReview',id:review.id,version:review.version,status:decision,replacementId:userId||null,response},'Решение по замене сохранено');}}><p>{review.requesterName} · {review.shiftTitle}</p><p className="service-body">{review.reason}</p><label className="field">Решение<select aria-label="Решение" value={decision} onChange={e=>setDecision(e.target.value)}><option value="accepted">Согласовать замену</option><option value="rejected">Отклонить заявку</option></select></label>{decision==='accepted'&&<MemberSelect label="Кто выйдет на смену" members={context.members.filter(m=>m.id!==review.requester_id)} value={userId} onChange={setUserId}/>}<label className="field">Ответ сотруднику<textarea aria-label="Ответ сотруднику" required minLength={10} maxLength={2000} rows={3} value={response} onChange={e=>setResponse(e.target.value)}/></label><ServiceFormError message={issue}/><button className="button primary" disabled={busy}>Сохранить решение</button></form></ServiceDialog>}
 </div>;
}
