import {useEffect,useState} from 'react';
import {Plus,ArrowLeft,Loader2,Pencil} from 'lucide-react';
import {toast} from 'sonner';
import {serviceApi,caseStatuses,type ServiceCase,type ServiceContext} from '@/lib/service-api';
import {errorMessage} from '@/lib/department-api';
import {formatSiteDate,toSiteDateTimeInput,fromSiteDateTimeInput} from '@/lib/date-time';
import {useServiceData} from './use-service-data';
import {ServiceHeading,ServiceLoad,ServiceRefresh,ServiceDialog,ServicePagination,ServiceFormError,MemberSelect} from './service-ui';
type Draft={id:string;version:number;assignedId:string;subject:string;body:string;dueAt:string;appealId:string;status:ServiceCase['status'];decision:string};
const path=(id?:string)=>'#department?tab=cases'+(id?'&case='+encodeURIComponent(id):'');
export default function ServiceCases({context,caseId}:{context:ServiceContext;caseId:string|null}) {
 const [status,setStatus]=useState('all'),[offset,setOffset]=useState(0),[draft,setDraft]=useState<Draft|null>(null),[busy,setBusy]=useState(false),[issue,setIssue]=useState('');
 const {data,loading,error,refresh}=useServiceData<{items:ServiceCase[];total:number}>({action:'cases',status,offset});
 const edit=(item?:ServiceCase)=>{setIssue('');setDraft(item?{id:item.id,version:item.version,assignedId:item.assigned_id||'',subject:item.subject,body:item.body,dueAt:item.due_at?toSiteDateTimeInput(item.due_at):'',appealId:item.appeal_id||'',status:item.status,decision:item.decision}:{id:crypto.randomUUID(),version:0,assignedId:'',subject:'',body:'',dueAt:'',appealId:'',status:'open',decision:''});};
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(!draft||busy)return;setBusy(true);setIssue('');try{await serviceApi({action:'caseSave',...draft,dueAt:draft.dueAt?fromSiteDateTimeInput(draft.dueAt):null,appealId:draft.appealId||null});setDraft(null);refresh();window.location.hash=path(draft.id);toast.success('Служебная проверка сохранена');window.dispatchEvent(new Event('usb-case-changed'));}catch(cause){setIssue(errorMessage(cause));}finally{setBusy(false);}};
 return <div className="service-tools"><ServiceHeading title="Служебные проверки" description={context.canManage?'Назначайте исполнителя, собирайте материалы и фиксируйте итоговое решение.':'Ваши назначенные проверки и материалы по ним.'} actions={<><ServiceRefresh refresh={()=>{refresh();window.dispatchEvent(new Event('usb-case-changed'));}} busy={busy}/>{context.canManage&&<button type="button" className="button primary" onClick={()=>edit()}><Plus size={17}/>Создать проверку</button>}</>}/>{caseId?<CaseDetail key={caseId} id={caseId} canManage={context.canManage} edit={edit}/>:<><div className="portal-actions service-filters"><label className="field">Статус<select aria-label="Статус" value={status} onChange={e=>{setStatus(e.target.value);setOffset(0);}}><option value="all">Все проверки</option>{Object.entries(caseStatuses).map(([id,title])=><option key={id} value={id}>{title}</option>)}</select></label></div><ServiceLoad loading={loading} error={error} refresh={refresh}/>{data&&!loading&&!error&&<><div className="service-case-list">{data.items.map(item=><a className="department-card service-case-card" key={item.id} href={path(item.id)}><span className="badge">{caseStatuses[item.status]}</span><h3>{item.subject}</h3><p>Исполнитель: {item.assigned_name||'Не назначен'}</p><small>Регистрация № {item.id}</small>{item.due_at&&<p className={item.status!=='closed'&&Date.parse(item.due_at)<Date.now()?'service-overdue':''}>Срок: {formatSiteDate(item.due_at)}</p>}</a>)}</div>{!data.items.length&&<div className="department-empty"><h3>Проверок пока нет</h3><p>{context.canManage?'Создайте проверку и назначьте ответственного сотрудника.':'Назначенные вам проверки появятся здесь.'}</p></div>}<ServicePagination offset={offset} total={data.total} onChange={setOffset}/></>}</>}
 {draft&&<ServiceDialog title={draft.version?'Изменить проверку':'Новая служебная проверка'} description="Материалы видят руководство и назначенный исполнитель." busy={busy} onClose={()=>setDraft(null)}><form className="portal-form" onSubmit={save}><label className="field">Тема проверки<input required minLength={5} maxLength={160} value={draft.subject} onChange={e=>setDraft({...draft,subject:e.target.value})}/></label><label className="field">Обстоятельства и задачи<textarea aria-label="Обстоятельства и задачи" required minLength={20} maxLength={12000} rows={4} value={draft.body} onChange={e=>setDraft({...draft,body:e.target.value})}/></label><MemberSelect members={context.members} value={draft.assignedId} onChange={assignedId=>setDraft({...draft,assignedId})}/><div className="portal-form-row"><label className="field">Срок по МСК<input type="datetime-local" value={draft.dueAt} onChange={e=>setDraft({...draft,dueAt:e.target.value})}/></label><label className="field">Статус проверки<select aria-label="Статус проверки" value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value as Draft['status']})}>{Object.entries(caseStatuses).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label></div><label className="field">Номер связанного обращения (необязательно)<input value={draft.appealId} maxLength={36} onChange={e=>setDraft({...draft,appealId:e.target.value})} placeholder="Регистрационный номер обращения"/></label><label className="field">Итоговое решение<textarea aria-label="Итоговое решение" required={draft.status==='closed'} minLength={draft.status==='closed'?20:0} rows={3} maxLength={6000} value={draft.decision} onChange={e=>setDraft({...draft,decision:e.target.value})}/></label><ServiceFormError message={issue}/><div className="portal-actions"><button type="button" className="button outline" disabled={busy} onClick={()=>setDraft(null)}>Отмена</button><button className="button primary" disabled={busy}>{busy&&<Loader2 size={17} className="spin"/>}Сохранить проверку</button></div></form></ServiceDialog>}</div>;
}
function CaseDetail({id,canManage,edit}:{id:string;canManage:boolean;edit:(item:ServiceCase)=>void}) {
 const {data,loading,error,refresh}=useServiceData<ServiceCase>({action:'case',id});const [body,setBody]=useState(''),[evidence,setEvidence]=useState(''),[busy,setBusy]=useState(false),[issue,setIssue]=useState(''),[noteId,setNoteId]=useState(()=>crypto.randomUUID());
 useEffect(()=>{window.addEventListener('usb-case-changed',refresh);return()=>window.removeEventListener('usb-case-changed',refresh);},[refresh]);
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(busy)return;setBusy(true);setIssue('');try{await serviceApi({action:'caseNote',id,noteId,body,evidence:evidence.split('\n').map(x=>x.trim()).filter(Boolean)});setBody('');setEvidence('');setNoteId(crypto.randomUUID());refresh();toast.success('Материал добавлен');}catch(cause){setIssue(errorMessage(cause));}finally{setBusy(false);}};
 return <><a className="department-back" href={path()}><ArrowLeft size={17}/>К списку проверок</a><ServiceLoad loading={loading} error={error} refresh={refresh}/>{data&&!loading&&!error&&<article className="department-card service-case-detail"><div className="portal-heading"><span className="badge">{caseStatuses[data.status]}</span>{canManage&&<button type="button" className="button outline" onClick={()=>edit(data)}><Pencil size={16}/>Изменить проверку</button>}</div><h3>{data.subject}</h3><p className="service-record-number">Регистрация № {data.id}</p><p>Исполнитель: {data.assigned_name||'Не назначен'}</p><p className="service-body">{data.body}</p>{data.due_at&&<p>Срок: {formatSiteDate(data.due_at)}</p>}{data.appeal_id&&canManage&&<a className="text-button" href={'#department?tab=appeals&appeal='+encodeURIComponent(data.appeal_id)}>Открыть связанное обращение</a>}{data.decision&&<div className="service-decision"><h4>Решение руководства</h4><p className="service-body">{data.decision}</p></div>}<h4>Материалы и история</h4><ol className="service-case-events">{data.events?.map(event=><li key={event.id}><strong>{event.actor_login}</strong><time dateTime={event.created_at}>{formatSiteDate(event.created_at)}</time><p className="service-body">{event.body}</p>{event.evidence.length>0&&<ul>{event.evidence.map((url,i)=><li key={i}><a href={url} target="_blank" rel="noopener noreferrer">Материал {i+1} ↗</a></li>)}</ul>}</li>)}</ol>{data.status!=='closed'&&<form className="portal-form service-case-note" onSubmit={save}><h4>Добавить материал</h4><label className="field">Описание материала<textarea aria-label="Описание материала" required minLength={10} maxLength={6000} rows={3} value={body} onChange={e=>setBody(e.target.value)}/></label><label className="field">Ссылки на доказательства<textarea aria-label="Ссылки на доказательства" rows={2} maxLength={21000} value={evidence} onChange={e=>setEvidence(e.target.value)} placeholder="До 10 ссылок HTTPS, каждая с новой строки"/></label><ServiceFormError message={issue}/><button className="button primary" disabled={busy}>{busy&&<Loader2 size={17} className="spin"/>}Добавить материал</button></form>}</article>}</>;
}
