import { useEffect, useState } from 'react';
import { Check, BookOpen, ShieldCheck, Send, Settings2, Search, ExternalLink } from 'lucide-react';
import { toast } from 'sonner';
import { trainingApi, useTraining, type Clearance, type ClearanceStatus } from '@/lib/training-api';
import { formatSiteDate } from '@/lib/date-time';
import { dashboardApi } from '@/lib/dashboard-api';
import { TrainingLoad } from './training-center';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
const labels:Record<ClearanceStatus,string>={preparing:'Идёт подготовка',pending:'На рассмотрении',approved:'Допуск подтверждён',rejected:'Нужна доработка',revoked:'Допуск отозван',outdated:'Программа изменилась'};
type Person={userId:string;login:string;state:Clearance};
export default function Admission({management}:{management:boolean}){
  const own=useTraining<Clearance>({op:'overview'});
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[settings,setSettings]=useState(false),[selected,setSelected]=useState<string[]>([]);
  useEffect(()=>{if(own.data)setSelected(own.data.tests.map(t=>t.id));},[own.data]);
  const act=async(payload:Record<string,unknown>)=>{setBusy(true);setError('');try{await trainingApi(payload);own.refresh();toast.success('Сохранено');}catch(e:any){setError(e.message);}finally{setBusy(false);}};
  if(own.loading||!own.data)return <TrainingLoad error={own.error} refresh={own.refresh}/>;
  const data=own.data;
  const materialCount=data.materials.filter(m=>m.readAt).length,passed=data.tests.filter(t=>t.passed).length;
  return <>
    {management?<><div className="training-section-heading"><div><h2>Подготовка сотрудников</h2><p>Допуск подтверждают владелец и заместитель после выполнения программы.</p></div><button className="button outline" onClick={()=>setSettings(v=>!v)}><Settings2 size={17}/>Программа подготовки</button></div>
      {settings&&<form className="training-panel program-form" onSubmit={e=>{e.preventDefault();act({action:'saveProgram',version:data.programVersion,requiredTests:selected});}}><h3>Обязательные тесты</h3><p>Выберите от 1 до 12 тестов. Изменение списка создаёт новую версию программы: ознакомление и допуски нужно подтвердить заново. Старые результаты сохраняются.</p>
        <div className="program-options">{data.availableTests?.map(t=><label className="portal-checkbox" key={t.id}><input type="checkbox" checked={selected.includes(t.id)} onChange={e=>setSelected(prev=>e.target.checked?[...prev,t.id]:prev.filter(id=>id!==t.id))}/>{t.title}</label>)}</div><button className="button primary" disabled={busy||selected.length<1||selected.length>12}>Сохранить программу</button></form>}
      {error&&<p className="inline-error" role="alert">{error}</p>}<Team key={data.programVersion}/></>:<>
      <div className={'training-panel clearance-banner state-'+data.status}><span className="clearance-icon"><ShieldCheck size={31}/></span><div><span className="eyebrow">МОЯ ПОДГОТОВКА · ПРОГРАММА {data.programVersion}</span><h2>{labels[data.status]}</h2><p>{data.status==='approved'?'Руководитель подтвердил прохождение программы подготовки.':data.status==='pending'?'Материалы и тесты пройдены. Заявка ожидает решения руководителя.':'Пройди три этапа, чтобы получить подтверждение руководителя.'}</p>{data.decidedAt&&<small>{data.decidedBy} · {formatSiteDate(data.decidedAt)}</small>}{data.note&&<p className="decision-note">Комментарий: {data.note}</p>}</div></div>
      <ol className="training-steps"><li className={materialCount===data.materials.length?'done':''}><span>01</span><strong>Изучить материалы</strong><small>{materialCount} из {data.materials.length}</small></li><li className={data.tests.length>0&&passed===data.tests.length?'done':''}><span>02</span><strong>Пройти тесты</strong><small>{passed} из {data.tests.length}</small></li><li className={data.status==='approved'?'done':''}><span>03</span><strong>Получить допуск</strong><small>{data.status==='approved'?'Подтверждён':'Решение руководителя'}</small></li></ol>
      <h2 className="training-subtitle">Материалы для изучения</h2><div className="training-grid">{data.materials.map(m=><article key={m.id} className="training-panel material-card"><BookOpen size={24}/><h3>{m.title}</h3><p>{m.description}</p><div className="material-links"><a className="text-button" href={m.href} target="_blank" rel="noopener noreferrer">Открыть материал <ExternalLink size={14}/></a>{m.id==='road-law'&&<a className="text-button" href="#laws?document=traffic-rules" target="_blank" rel="noopener noreferrer">Открыть ПДД <ExternalLink size={14}/></a>}</div><button className={'button '+(m.readAt?'outline':'primary')} disabled={busy||!!m.readAt} onClick={()=>act({action:'ackMaterial',id:m.id,version:data.programVersion})}>{m.readAt?<><Check size={16}/>Изучено</>:'Материал изучен'}</button></article>)}</div>
      <h2 className="training-subtitle">Обязательные тесты</h2><div className="training-panel">{!data.tests.length?<p>Руководитель ещё не выбрал обязательные тесты.</p>:data.tests.map(t=><div className="required-test" key={t.id}><span className={'requirement-dot '+(t.passed?'done':'')}><Check size={17}/></span><div><strong>{t.title}</strong><small>{!t.published?'Тест снят с публикации — обратитесь к руководителю':t.passed?`Пройден · ${formatSiteDate(t.passedAt!)}`:'Нужен зачёт по текущей редакции теста'}</small></div>{!t.passed&&t.published&&<a className="button outline" href="#tests">К тестам</a>}</div>)}</div>
      <div className="training-panel request-clearance"><div><h3>Подтверждение руководителя</h3><p>Отметки об изучении ты ставишь самостоятельно. Результаты тестов проверяются автоматически. Допуск действует внутри подразделения игрового проекта.</p></div><button className="button primary" disabled={busy||!data.ready||['pending','approved'].includes(data.status)} onClick={()=>act({action:'requestClearance'})}><Send size={17}/>{data.status==='pending'?'Заявка отправлена':data.status==='approved'?'Допуск подтверждён':'Подать заявку'}</button></div>
      {error&&<p className="inline-error" role="alert">{error}</p>}
    </>}
  </>;
}
const personFromHash=()=>new URLSearchParams(window.location.hash.split('?')[1]||'').get('person')||'';
function Team(){
  const [input,setInput]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState(0);
  const query=useTraining<{people:Person[];total:number}>({op:'clearanceTeam',search,page});
  const [person,setPerson]=useState<Person|null>(null),[status,setStatus]=useState('approved'),[note,setNote]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const [targetId,setTargetId]=useState(personFromHash),[targetRevision,setTargetRevision]=useState(0),[targetLoading,setTargetLoading]=useState(false),[targetError,setTargetError]=useState('');
  useEffect(()=>{const update=()=>setTargetId(personFromHash());window.addEventListener('hashchange',update);return()=>window.removeEventListener('hashchange',update);},[]);
  useEffect(()=>{
    let active=true;setTargetError('');setTargetLoading(false);
    if(!targetId)return;
    setPerson(null);setTargetLoading(true);
    dashboardApi<Person>({action:'clearance',userId:targetId}).then(next=>{if(active){setPerson(next);setStatus(next.state.status==='pending'?'approved':'revoked');setNote('');setError('');}})
      .catch(cause=>{if(active)setTargetError(cause.message);}).finally(()=>{if(active)setTargetLoading(false);});
    return()=>{active=false;};
  },[targetId,targetRevision]);
  const decide=async(e:React.FormEvent)=>{e.preventDefault();if(!person)return;setBusy(true);setError('');try{await trainingApi({action:'decideClearance',userId:person.userId,status,note});setPerson(null);query.refresh();toast.success('Решение сохранено');}catch(e:any){setError(e.message);}finally{setBusy(false);}};
  return <>{targetLoading&&<p role="status">Загружаем заявку сотрудника…</p>}{targetError&&<div className="error-banner" role="alert"><span>{targetError}</span><button type="button" className="button outline" onClick={()=>setTargetRevision(n=>n+1)}>Повторить</button></div>}<form className="training-search" onSubmit={e=>{e.preventDefault();setSearch(input);setPage(0);}}><label className="field"><span className="sr-only">Поиск сотрудника по логину</span><input value={input} maxLength={100} onChange={e=>setInput(e.target.value)} placeholder="Логин сотрудника"/></label><button className="button outline"><Search size={17}/>Найти</button></form>
    {query.loading||!query.data?<TrainingLoad error={query.error} refresh={query.refresh}/>:<><div className="training-team-list">{query.data.people.map(p=><article className="training-panel trainee-row" key={p.userId}><div><h3>{p.login}</h3><span className={'clearance-status state-'+p.state.status}>{labels[p.state.status]}</span><p>Материалы: {p.state.materials.filter(m=>m.readAt).length}/{p.state.materials.length} · Тесты: {p.state.tests.filter(t=>t.passed).length}/{p.state.tests.length}</p></div><button className="button outline" onClick={()=>{setPerson(p);setStatus(p.state.status==='pending'?'approved':'revoked');setNote('');setError('');}}>Открыть подготовку</button></article>)}{!query.data.people.length&&<p className="training-panel">Сотрудники не найдены.</p>}</div><div className="training-pagination"><button className="button outline" disabled={!page} onClick={()=>setPage(p=>p-1)}>Назад</button><span>{page+1} / {Math.max(1,Math.ceil(query.data.total/30))}</span><button className="button outline" disabled={(page+1)*30>=query.data.total} onClick={()=>setPage(p=>p+1)}>Далее</button></div></>}
    <Dialog open={!!person} onOpenChange={v=>{if(!v&&!busy)setPerson(null);}}><DialogContent className="portal-editor"><DialogHeader><DialogTitle>{person?.login}</DialogTitle><DialogDescription>Подготовка к самостоятельной службе</DialogDescription></DialogHeader>{person&&<form className="portal-form" onSubmit={decide}><strong>{labels[person.state.status]}</strong><ul className="training-checklist">{person.state.materials.map(m=><li key={m.id}>{m.readAt?'✓':'○'} {m.title}</li>)}{person.state.tests.map(t=><li key={t.id}>{t.passed?'✓':'○'} {t.title}</li>)}</ul>{person.state.note&&<p>{person.state.note}</p>}{['pending','approved','outdated'].includes(person.state.status)&&<><label className="field">Решение<select value={status} onChange={e=>setStatus(e.target.value)}>{person.state.status==='pending'?<><option value="approved">Подтвердить допуск</option><option value="rejected">Вернуть на доработку</option></>:<option value="revoked">Отозвать допуск</option>}</select></label><label className="field">Комментарий<textarea value={note} maxLength={600} required={status!=='approved'} minLength={status!=='approved'?3:0} onChange={e=>setNote(e.target.value)}/></label><button className="button primary" disabled={busy}>Сохранить решение</button></>}{error&&<p className="inline-error" role="alert">{error}</p>}</form>}</DialogContent></Dialog>
  </>;
}
