import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
export async function checkPortal({db,asUser,denied,A,B,C,checks}){
  const api=async payload=>(await db.query('select public.knowledge_portal($1::jsonb) as data',[JSON.stringify(payload)])).rows[0].data;
  const draft={action:'saveAnnouncement',title:'Учебная аттестация',body:'Тестовый текст только в локальной БД.',kind:'attestation',eventAt:'2030-10-01T10:00:00Z',pinned:true,published:false};
  const link={action:'saveLink',title:'Учебная форма',description:'Локальная проверка',url:'https://example.com/report',category:'reports',position:5,published:false};
  await db.exec('reset role');
  await db.query("insert into knowledge_private.test_creators(user_id,role) values($1,'owner'),($2,'author'),($3,'deputy') on conflict(user_id) do update set role=excluded.role",[A,B,C]);
  await asUser(null,'anon');
  assert.equal((await api({op:'links'})).links.length,4);
  assert.deepEqual((await api({op:'announcements'})).announcements,[]);
  for(const op of ['bookmarks','setBookmark','manageAnnouncements','manageLinks','saveAnnouncement','saveLink'])await denied(()=>api({op}),'PT401');
  for(const table of ['law_article_refs','law_bookmarks','announcements','useful_links'])await denied(()=>db.query(`select * from knowledge_private.${table}`),'42501');
  await denied(()=>db.query("select knowledge_private.workspace_core('{}'::jsonb)"),'42501');
  await denied(()=>db.query("select knowledge_private.workspace_roles('{}'::jsonb)"),'42501');
  await denied(()=>db.query("select knowledge_private.text_field('\"x\"','x',1,2)"),'42501');
  checks.push('Portal guests see published content only; personal/editorial operations and private data remain closed');
  await asUser(A);
  let bookmarks=await api({action:'setBookmark',document:'criminal',article:'article-6',saved:true,userId:B});
  assert.deepEqual(bookmarks.bookmarks,[{document:'criminal',article:'article-6'}]);
  await api({action:'setBookmark',document:'criminal',article:'article-6',saved:true});
  assert.equal((await api({op:'bookmarks'})).bookmarks.length,1);
  await denied(()=>api({action:'setBookmark',document:'criminal',article:'article-999999',saved:true}),'PT404');
  await denied(()=>api({action:'setBookmark',document:'criminal',article:'article-6',saved:'false'}),'PT400');
  await asUser(B);assert.deepEqual((await api({op:'bookmarks',userId:A})).bookmarks,[]);
  await api({action:'setBookmark',document:'charter',article:'article-8',saved:true});
  await api({action:'setBookmark',document:'criminal',article:'article-6',saved:false,userId:A});
  await asUser(A);assert.equal((await api({op:'bookmarks'})).bookmarks.length,1);
  await api({action:'setBookmark',document:'criminal',article:'article-6',saved:false});
  assert.equal((await api({op:'bookmarks'})).bookmarks.length,0);
  checks.push('Bookmarks belong exclusively to auth.uid(), survive repeat requests, reject missing articles and ignore spoofed user IDs');
  await asUser(B);for(const op of ['manageAnnouncements','manageLinks'])await denied(()=>api({op,role:'owner'}),'PT403');
  await db.query("select set_config('request.jwt.claims',$1,false)",[JSON.stringify({sub:B,user_metadata:{role:'owner'},app_metadata:{role:'owner'}})]);
  await denied(()=>api({...draft,role:'owner'}),'PT403');await denied(()=>api(link),'PT403');
  await asUser(A);const saved=await api(draft);assert.equal(saved.version,1);
  const savedLink=await api(link);
  assert.equal((await api({op:'manageAnnouncements'})).announcements[0].id,saved.id);
  assert.equal((await api({op:'announcements'})).announcements.length,0);
  await asUser(null,'anon');assert.equal((await api({op:'announcements'})).announcements.length,0);assert.equal((await api({op:'links'})).links.length,4);
  checks.push('Only live owner/deputy grants enable editing; forged JWT metadata cannot reveal drafts or publish');
  await asUser(C);const publication=await api({...draft,id:saved.id,version:1,published:true});assert.equal(publication.version,2);
  await denied(()=>api({...draft,id:saved.id,version:1,published:true,title:'Устаревшая правка'}),'PT409');
  const publishedLink=await api({...link,id:savedLink.id,version:1,published:true});assert.equal(publishedLink.version,2);
  await denied(()=>api({...link,id:savedLink.id,version:1,published:true}),'PT409');
  await asUser(null,'anon');const feed=(await api({op:'announcements'})).announcements;
  assert.equal(feed.length,1);assert.equal(feed[0].title,draft.title);assert.equal(feed[0].eventAt,'2030-10-01T10:00:00+00:00');assert.equal(feed[0].pinned,true);
  assert.equal((await api({op:'links'})).links.length,5);
  await asUser(A);await api({...draft,id:saved.id,version:2,published:false});await api({...link,id:savedLink.id,version:2,published:false});
  await asUser(null,'anon');assert.equal((await api({op:'announcements'})).announcements.length,0);assert.equal((await api({op:'links'})).links.length,4);
  checks.push('Owner/deputy publication, pinning, event time, withdrawal and optimistic edit conflicts work');
  await asUser(A);
  for(const url of ['javascript:alert(1)','data:text/html,test','http://example.com','https://user:password@example.com','https://example.com:99999/','https://example.com/\nattack'])await denied(()=>api({...link,url}),'PT400');
  for(const payload of [{...link,category:'admin'},{...link,position:1001},{...draft,kind:'admin'},{...draft,eventAt:'infinity'},{...draft,body:'x'.repeat(6001)},{...draft,published:'true'},[],null])await denied(()=>api(payload),'PT400');
  checks.push('Portal rejects unsafe links, unknown categories, bad dates, malformed publication flags and oversized content');
  await db.exec('reset role');await db.query("delete from knowledge_private.test_creators where user_id=$1",[C]);await asUser(C);await denied(()=>api(draft),'PT403');
  await db.exec('reset role');await db.query("update auth.users set email_confirmed_at=null where id=$1",[B]);await asUser(B);await denied(()=>api({op:'bookmarks'}),'PT401');
  await db.exec('reset role');await db.query("update auth.users set email_confirmed_at=now() where id=$1",[B]);
  const rls=(await db.query("select relname,relrowsecurity from pg_class where relnamespace='knowledge_private'::regnamespace and relname in ('law_article_refs','law_bookmarks','announcements','useful_links')")).rows;
  assert.equal(rls.length,4);assert(rls.every(row=>row.relrowsecurity));
  const exposed=(await db.query("select p.proname from pg_proc p where p.pronamespace='knowledge_private'::regnamespace and has_function_privilege('anon',p.oid,'execute')")).rows;
  assert.deepEqual(exposed.map(row=>row.proname).sort(),['portal','signup_check']);
  checks.push('Revocation takes effect immediately; unconfirmed accounts cannot bookmark; RLS and private helper privileges stay restricted');
  const module=ts.transpileModule(fs.readFileSync(new URL('../lib/law-search.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ES2022,target:ts.ScriptTarget.ES2022}}).outputText;
  const {matchesLaw,lawExcerpt}=await import('data:text/javascript;base64,'+Buffer.from(module).toString('base64'));
  const entry=(title,body)=>({kind:'article',id:'article-1',title,paragraphs:[body],chapter:'Глава I',page:1});
  assert(matchesLaw(entry('Статья 1.2 Законность',''),'1.2'));assert(!matchesLaw(entry('Статья 1.2 Законность',''),'1'));
  assert(matchesLaw(entry('Статья 1.2 Законность',''),'ст. 1.2'));assert(matchesLaw(entry('Статья 1.2 Законность',''),'Статья 1.2.'));
  assert(matchesLaw(entry('Пункт 8.2.','Ограничения скорости'),'8.2'));
  assert(matchesLaw(entry('Пункт 8.2.','Ограничения скорости'),'п. 8.2'));
  assert(matchesLaw(entry('Пункт 8.2.','Ограничения скорости'),'Пункт 8.2.'));
  assert(!matchesLaw(entry('Пункт 8.2.','Ограничения скорости'),'ст. 8.2'));
  assert(!matchesLaw(entry('Статья 8.2. Дискриминация',''),'п. 8.2'));
  assert(!matchesLaw(entry('Пункт 8.2.','Ограничения скорости'),'8'));
  assert(matchesLaw(entry('Статья 3','Учёт\n   доказательств'),'УЧЕТ доказательств'));
  assert(!matchesLaw(entry('Статья 3','Фраза'),'несуществующее'));
  const metadata=JSON.parse(fs.readFileSync(new URL('../lib/law-documents.json',import.meta.url),'utf8'));
  const bodies=metadata.map(doc=>JSON.parse(fs.readFileSync(new URL(`../public/laws/${doc.id}.json`,import.meta.url),'utf8')));
  const articles=bodies.flatMap(doc=>doc.entries.filter(item=>item.kind==='article'));
  assert.equal(articles.length,812);assert(bodies.filter(doc=>doc.entries.some(e=>e.kind==='article'&&matchesLaw(e,'задержан'))).length>1);
  for(const meta of metadata){
    const body=bodies.find(doc=>doc.id===meta.id);
    assert.equal(body.entries.filter(e=>e.kind==='article').length,meta.articleCount);
    assert.equal(new Set(body.entries.map(e=>e.id)).size,body.entries.length);
  }
  const road=bodies.find(doc=>doc.id==='traffic-rules');
  assert.equal(road.entries.filter(e=>matchesLaw(e,'п. 4.1')).length,1);
  assert(road.entries.find(e=>matchesLaw(e,'п. 4.1')).paragraphs.join(' ').includes('неотложного служебного задания'));
  const refs=(await db.query('select document_id,article_id from knowledge_private.law_article_refs order by document_id,article_id')).rows;
  assert.deepEqual(refs.map(r=>`${r.document_id}/${r.article_id}`).sort(),bodies.flatMap(doc=>doc.entries.filter(e=>e.kind==='article').map(e=>`${doc.id}/${e.id}`)).sort());
  await asUser(A);
  await api({action:'setBookmark',document:'traffic-rules',article:'article-65',saved:true});
  await api({action:'setBookmark',document:'administrative',article:'article-38',saved:true});
  assert.equal((await api({op:'bookmarks'})).bookmarks.length,2);
  await asUser(B);assert.deepEqual((await api({op:'bookmarks'})).bookmarks,[{document:'charter',article:'article-8'}]);
  await asUser(A);
  await api({action:'setBookmark',document:'traffic-rules',article:'article-65',saved:false});
  await api({action:'setBookmark',document:'administrative',article:'article-38',saved:false});
  assert(lawExcerpt(entry('Статья 1','А'.repeat(300)+' искомая фраза '+'Б'.repeat(300)),'искомая фраза').includes('искомая фраза'));
  checks.push('Global search covers all 812 articles/points, distinguishes point/article prefixes, and preserves exact numbers; all references match the database and new bookmarks stay private');
}
