-- Public content is explicitly published; personal bookmarks stay behind auth.uid().
create table knowledge_private.law_article_refs (
  document_id text not null,
  article_id text not null,
  primary key(document_id,article_id)
);
create table knowledge_private.law_bookmarks (
  user_id uuid not null references auth.users(id) on delete cascade,
  document_id text not null,
  article_id text not null,
  created_at timestamptz not null default now(),
  primary key(user_id,document_id,article_id),
  foreign key(document_id,article_id) references knowledge_private.law_article_refs(document_id,article_id) on delete cascade
);
create index law_bookmarks_article on knowledge_private.law_bookmarks(document_id,article_id);
create table knowledge_private.announcements (
  id uuid primary key default gen_random_uuid(),
  title text not null check(char_length(title) between 3 and 140),
  body text not null check(char_length(body) between 1 and 6000),
  kind text not null check(kind in ('news','rules','attestation')),
  event_at timestamptz,
  pinned boolean not null default false,
  published boolean not null default false,
  published_at timestamptz,
  updated_at timestamptz not null default now(),
  version integer not null default 1,
  check(not published or published_at is not null)
);
create index announcements_feed on knowledge_private.announcements(pinned desc,published_at desc) where published;
create table knowledge_private.useful_links (
  id uuid primary key default gen_random_uuid(),
  title text not null check(char_length(title) between 3 and 120),
  description text not null default '' check(char_length(description)<=300),
  url text not null check(char_length(url)<=1500 and url ~ '^https://[A-Za-z0-9.-]+\.[A-Za-z]{2,}(:[0-9]{1,5})?([/?#][^[:space:]<>]*)?$'),
  category text not null check(category in ('forum','appeals','reports','contact')),
  position integer not null default 0 check(position between 0 and 1000),
  published boolean not null default true,
  updated_at timestamptz not null default now(),
  version integer not null default 1
);
alter table knowledge_private.law_article_refs enable row level security;
alter table knowledge_private.law_bookmarks enable row level security;
alter table knowledge_private.announcements enable row level security;
alter table knowledge_private.useful_links enable row level security;
revoke all on knowledge_private.law_article_refs,knowledge_private.law_bookmarks,knowledge_private.announcements,knowledge_private.useful_links from public,anon,authenticated;

insert into knowledge_private.law_article_refs(document_id,article_id) values
('charter','article-3'),
('charter','article-4'),
('charter','article-5'),
('charter','article-6'),
('charter','article-8'),
('charter','article-9'),
('charter','article-10'),
('charter','article-12'),
('charter','article-13'),
('charter','article-14'),
('charter','article-16'),
('charter','article-17'),
('charter','article-18'),
('charter','article-20'),
('charter','article-21'),
('charter','article-22'),
('charter','article-24'),
('charter','article-25'),
('charter','article-27'),
('charter','article-28'),
('charter','article-30'),
('charter','article-31'),
('charter','article-32'),
('charter','article-33'),
('charter','article-35'),
('charter','article-36'),
('charter','article-37'),
('charter','article-38'),
('charter','article-39'),
('charter','article-40'),
('charter','article-42'),
('charter','article-44'),
('charter','article-46'),
('criminal','article-4'),
('criminal','article-5'),
('criminal','article-6'),
('criminal','article-7'),
('criminal','article-8'),
('criminal','article-9'),
('criminal','article-10'),
('criminal','article-11'),
('criminal','article-12'),
('criminal','article-13'),
('criminal','article-14'),
('criminal','article-15'),
('criminal','article-18'),
('criminal','article-19'),
('criminal','article-20'),
('criminal','article-21'),
('criminal','article-22'),
('criminal','article-23'),
('criminal','article-24'),
('criminal','article-26'),
('criminal','article-27'),
('criminal','article-28'),
('criminal','article-29'),
('criminal','article-30'),
('criminal','article-31'),
('criminal','article-32'),
('criminal','article-33'),
('criminal','article-35'),
('criminal','article-36'),
('criminal','article-37'),
('criminal','article-38'),
('criminal','article-39'),
('criminal','article-40'),
('criminal','article-41'),
('criminal','article-44'),
('criminal','article-45'),
('criminal','article-46'),
('criminal','article-47'),
('criminal','article-48'),
('criminal','article-49'),
('criminal','article-50'),
('criminal','article-51'),
('criminal','article-52'),
('criminal','article-53'),
('criminal','article-54'),
('criminal','article-55'),
('criminal','article-56'),
('criminal','article-57'),
('criminal','article-59'),
('criminal','article-63'),
('criminal','article-64'),
('criminal','article-65'),
('criminal','article-66'),
('criminal','article-67'),
('criminal','article-68'),
('criminal','article-69'),
('criminal','article-70'),
('criminal','article-71'),
('criminal','article-73'),
('criminal','article-74'),
('criminal','article-75'),
('criminal','article-76'),
('criminal','article-77'),
('criminal','article-78'),
('criminal','article-80'),
('criminal','article-81'),
('criminal','article-82'),
('criminal','article-83'),
('criminal','article-84'),
('criminal','article-85'),
('criminal','article-87'),
('criminal','article-88'),
('criminal','article-89'),
('criminal','article-90'),
('criminal','article-91'),
('criminal','article-92'),
('criminal','article-93'),
('criminal','article-96'),
('criminal','article-97'),
('criminal','article-98'),
('criminal','article-99'),
('criminal','article-100'),
('criminal','article-101'),
('criminal','article-102'),
('criminal','article-103'),
('criminal','article-104'),
('criminal','article-105'),
('criminal','article-106'),
('criminal','article-107'),
('criminal','article-108'),
('criminal','article-109'),
('criminal','article-110'),
('criminal','article-111'),
('criminal','article-113'),
('criminal','article-114'),
('criminal','article-115'),
('criminal','article-116'),
('criminal','article-117'),
('criminal','article-118'),
('criminal','article-119'),
('criminal','article-120'),
('criminal','article-121'),
('criminal','article-122'),
('criminal','article-123'),
('criminal','article-124'),
('criminal','article-125'),
('criminal','article-128'),
('criminal','article-129'),
('criminal','article-130'),
('criminal','article-131'),
('criminal','article-132'),
('criminal','article-133'),
('criminal','article-134'),
('criminal','article-135'),
('criminal','article-136'),
('criminal','article-137'),
('criminal','article-138'),
('criminal','article-139'),
('criminal','article-140'),
('criminal','article-141'),
('criminal','article-142'),
('criminal','article-143'),
('criminal','article-144'),
('criminal','article-145'),
('criminal','article-146'),
('criminal','article-147'),
('criminal','article-148'),
('criminal','article-150'),
('criminal','article-151'),
('criminal','article-152'),
('criminal','article-153'),
('criminal','article-154'),
('criminal','article-155'),
('criminal','article-156'),
('criminal','article-159'),
('criminal','article-160'),
('criminal','article-161'),
('criminal','article-162'),
('criminal','article-163'),
('criminal','article-164'),
('criminal','article-165'),
('criminal','article-166'),
('criminal','article-167'),
('criminal','article-168'),
('criminal','article-170'),
('criminal','article-171'),
('criminal','article-172'),
('criminal','article-173'),
('criminal','article-174'),
('criminal','article-175'),
('criminal','article-176'),
('criminal','article-177'),
('criminal','article-178'),
('criminal','article-179'),
('criminal','article-181'),
('criminal','article-182'),
('criminal','article-183'),
('criminal','article-184'),
('criminal','article-185'),
('criminal','article-186'),
('criminal','article-187'),
('criminal','article-188'),
('criminal','article-189'),
('criminal','article-190'),
('criminal','article-191'),
('criminal','article-192'),
('criminal','article-193'),
('criminal','article-194'),
('criminal','article-195'),
('criminal','article-196'),
('criminal','article-197'),
('criminal','article-198'),
('criminal','article-199'),
('criminal','article-200'),
('criminal','article-202'),
('criminal','article-203'),
('criminal','article-204'),
('criminal','article-205'),
('criminal','article-206'),
('criminal','article-207'),
('criminal','article-208'),
('criminal','article-209'),
('criminal','article-210'),
('criminal','article-211'),
('criminal','article-212'),
('criminal','article-213'),
('criminal','article-214'),
('criminal','article-215'),
('criminal','article-216'),
('criminal','article-217'),
('labour','article-4'),
('labour','article-5'),
('labour','article-6'),
('labour','article-7'),
('labour','article-8'),
('labour','article-9'),
('labour','article-10'),
('labour','article-11'),
('labour','article-12'),
('labour','article-15'),
('labour','article-16'),
('labour','article-17'),
('labour','article-18'),
('labour','article-19'),
('labour','article-20'),
('labour','article-22'),
('labour','article-23'),
('labour','article-24'),
('labour','article-25'),
('labour','article-26'),
('labour','article-27'),
('labour','article-28'),
('labour','article-29'),
('labour','article-30'),
('labour','article-31'),
('labour','article-32'),
('labour','article-33'),
('labour','article-34'),
('labour','article-37'),
('labour','article-38'),
('labour','article-39'),
('labour','article-40'),
('labour','article-41'),
('labour','article-42'),
('labour','article-43'),
('labour','article-44'),
('labour','article-45'),
('labour','article-48'),
('labour','article-49'),
('labour','article-50'),
('labour','article-51'),
('labour','article-52'),
('labour','article-53'),
('labour','article-56'),
('labour','article-57'),
('labour','article-58'),
('labour','article-59'),
('labour','article-60'),
('labour','article-61'),
('labour','article-62'),
('labour','article-65'),
('labour','article-66'),
('labour','article-67'),
('labour','article-68'),
('labour','article-69'),
('labour','article-70'),
('labour','article-71'),
('labour','article-72'),
('labour','article-75'),
('labour','article-76'),
('labour','article-77'),
('labour','article-78'),
('labour','article-79'),
('labour','article-80'),
('labour','article-81'),
('labour','article-84'),
('labour','article-85'),
('labour','article-86'),
('labour','article-87'),
('labour','article-88'),
('labour','article-89'),
('labour','article-90'),
('police','article-3'),
('police','article-4'),
('police','article-5'),
('police','article-6'),
('police','article-7'),
('police','article-8'),
('police','article-9'),
('police','article-10'),
('police','article-12'),
('police','article-13'),
('police','article-14'),
('police','article-15'),
('police','article-16'),
('police','article-17'),
('police','article-18'),
('police','article-20'),
('police','article-21'),
('police','article-22'),
('police','article-23'),
('police','article-24'),
('police','article-25'),
('police','article-26'),
('police','article-27'),
('police','article-28'),
('police','article-29'),
('police','article-30'),
('police','article-31'),
('police','article-32'),
('police','article-33'),
('police','article-34'),
('police','article-35'),
('police','article-37'),
('police','article-38'),
('police','article-39'),
('police','article-40'),
('police','article-41'),
('police','article-42'),
('police','article-43'),
('police','article-44'),
('police','article-45'),
('police','article-46'),
('police','article-47'),
('police','article-48'),
('police','article-49'),
('police','article-50'),
('police','article-51'),
('police','article-53'),
('police','article-54'),
('police','article-55'),
('police','article-56'),
('police','article-57'),
('police','article-58'),
('police','article-59'),
('police','article-60'),
('police','article-61'),
('police','article-63'),
('police','article-64'),
('police','article-65'),
('police','article-66'),
('police','article-67'),
('police','article-68'),
('police','article-70'),
('police','article-71'),
('police','article-72'),
('police','article-73'),
('police','article-74'),
('police','article-75'),
('police','article-76'),
('police','article-77'),
('police','article-78'),
('police','article-80'),
('police','article-81'),
('police','article-82'),
('police','article-83'),
('police','article-84'),
('police','article-85'),
('police','article-86'),
('procedure','article-2'),
('procedure','article-3'),
('procedure','article-4'),
('procedure','article-5'),
('procedure','article-6'),
('procedure','article-7'),
('procedure','article-8'),
('procedure','article-9'),
('procedure','article-10'),
('procedure','article-11'),
('procedure','article-12'),
('procedure','article-13'),
('procedure','article-14'),
('procedure','article-15'),
('procedure','article-16'),
('procedure','article-17'),
('procedure','article-18'),
('procedure','article-19'),
('procedure','article-20'),
('procedure','article-21'),
('procedure','article-23'),
('procedure','article-24'),
('procedure','article-25'),
('procedure','article-26'),
('procedure','article-27'),
('procedure','article-28'),
('procedure','article-29'),
('procedure','article-30'),
('procedure','article-31'),
('procedure','article-32'),
('procedure','article-33'),
('procedure','article-34'),
('procedure','article-35'),
('procedure','article-36'),
('procedure','article-37'),
('procedure','article-38'),
('procedure','article-39'),
('procedure','article-40'),
('procedure','article-41'),
('procedure','article-42'),
('procedure','article-43'),
('procedure','article-44'),
('procedure','article-45'),
('procedure','article-46'),
('procedure','article-47'),
('procedure','article-48'),
('procedure','article-49'),
('procedure','article-50'),
('procedure','article-51'),
('procedure','article-52'),
('procedure','article-53'),
('procedure','article-54'),
('procedure','article-55'),
('procedure','article-56'),
('procedure','article-57'),
('procedure','article-58'),
('procedure','article-59'),
('procedure','article-60'),
('procedure','article-62'),
('procedure','article-63'),
('procedure','article-64'),
('procedure','article-65'),
('procedure','article-66'),
('procedure','article-68'),
('procedure','article-69'),
('procedure','article-70'),
('procedure','article-71'),
('procedure','article-72'),
('procedure','article-73'),
('procedure','article-74'),
('procedure','article-75'),
('procedure','article-77'),
('procedure','article-78'),
('procedure','article-79'),
('procedure','article-80'),
('procedure','article-81'),
('procedure','article-82'),
('procedure','article-83'),
('procedure','article-84'),
('procedure','article-85'),
('procedure','article-86'),
('procedure','article-87'),
('procedure','article-88'),
('procedure','article-89'),
('procedure','article-90'),
('procedure','article-92'),
('procedure','article-93'),
('procedure','article-94'),
('procedure','article-95'),
('procedure','article-96'),
('procedure','article-98'),
('procedure','article-99'),
('procedure','article-100'),
('procedure','article-101'),
('procedure','article-102'),
('procedure','article-104'),
('procedure','article-105'),
('procedure','article-106'),
('procedure','article-107'),
('procedure','article-108'),
('procedure','article-109'),
('procedure','article-111'),
('procedure','article-112'),
('procedure','article-113'),
('procedure','article-114'),
('procedure','article-115'),
('procedure','article-116'),
('procedure','article-118'),
('procedure','article-119'),
('procedure','article-120'),
('procedure','article-121'),
('procedure','article-122'),
('procedure','article-123'),
('procedure','article-124'),
('procedure','article-125'),
('procedure','article-127'),
('procedure','article-128'),
('procedure','article-129'),
('procedure','article-130'),
('procedure','article-131'),
('procedure','article-132'),
('procedure','article-134'),
('procedure','article-136'),
('procedure','article-137'),
('traffic-police','article-3'),
('traffic-police','article-4'),
('traffic-police','article-5'),
('traffic-police','article-6'),
('traffic-police','article-7'),
('traffic-police','article-8'),
('traffic-police','article-9'),
('traffic-police','article-10'),
('traffic-police','article-12'),
('traffic-police','article-13'),
('traffic-police','article-14'),
('traffic-police','article-15'),
('traffic-police','article-16'),
('traffic-police','article-17'),
('traffic-police','article-18'),
('traffic-police','article-19'),
('traffic-police','article-21'),
('traffic-police','article-22'),
('traffic-police','article-23'),
('traffic-police','article-24'),
('traffic-police','article-25'),
('traffic-police','article-26'),
('traffic-police','article-27'),
('traffic-police','article-28'),
('traffic-police','article-29'),
('traffic-police','article-30'),
('traffic-police','article-31'),
('traffic-police','article-33'),
('traffic-police','article-34'),
('traffic-police','article-35'),
('traffic-police','article-36'),
('traffic-police','article-37'),
('traffic-police','article-38'),
('traffic-police','article-39'),
('traffic-police','article-41'),
('traffic-police','article-42'),
('traffic-police','article-43'),
('traffic-police','article-44'),
('traffic-police','article-45'),
('traffic-police','article-46'),
('traffic-police','article-48'),
('traffic-police','article-49'),
('traffic-police','article-50'),
('traffic-police','article-51'),
('traffic-police','article-52'),
('traffic-police','article-53'),
('traffic-police','article-54'),
('traffic-police','article-55'),
('traffic-police','article-56'),
('traffic-police','article-57'),
('traffic-police','article-59'),
('traffic-police','article-60'),
('traffic-police','article-61'),
('traffic-police','article-62'),
('traffic-police','article-63'),
('traffic-police','article-64'),
('traffic-police','article-65'),
('traffic-police','article-67'),
('traffic-police','article-68'),
('traffic-police','article-69'),
('traffic-police','article-70'),
('traffic-police','article-71'),
('traffic-police','article-72'),
('traffic-police','article-73'),
('traffic-police','article-74'),
('traffic-police','article-75'),
('traffic-police','article-77'),
('traffic-police','article-78'),
('traffic-police','article-79'),
('traffic-police','article-80'),
('traffic-police','article-81'),
('traffic-police','article-82'),
('traffic-police','article-83'),
('traffic-police','article-84'),
('traffic-police','article-85'),
('traffic-police','article-86'),
('traffic-police','article-87');

insert into knowledge_private.useful_links(title,description,url,category,position) values
('Форум «Россия Онлайн»','Официальный форум игрового проекта.','https://forum.russia.online/','forum',0),
('Внутренний устав ГИБДД','Тема форума, предоставленная для учебных материалов сайта.','https://forum.russia.online/threads/vnutrennii-ustav-gibdd.5291/','forum',10),
('Уголовный кодекс РО','Тема с уголовным законодательством игрового проекта.','https://forum.russia.online/threads/ugolovnyi-kodeks-ro.4805/','forum',20),
('Трудовой кодекс РО','Тема с правилами трудовых отношений и службы.','https://forum.russia.online/threads/trudovoi-kodeks-ro.4943/','forum',30);

create function knowledge_private.portal(payload jsonb default '{}'::jsonb)
returns jsonb language plpgsql security definer set search_path='' as $$
declare
  v_uid uuid := auth.uid(); v_op text; v_role text; v_id uuid;
  v_document text; v_article text; v_title text; v_body text; v_kind text;
  v_url text; v_description text; v_category text; v_position integer;
  v_published boolean; v_pinned boolean; v_event timestamptz; v_version integer;
  v_announcement knowledge_private.announcements; v_link knowledge_private.useful_links;
begin
  if jsonb_typeof(payload) is distinct from 'object' or octet_length(payload::text)>40000 then
    raise exception using errcode='PT400',message='Некорректные данные.';
  end if;
  v_op:=coalesce(payload->>'action',payload->>'op','announcements');
  -- Only these two reads are public, and their queries exclude drafts.
  if v_op not in ('announcements','links') then
    if v_uid is null or not exists(select 1 from auth.users where id=v_uid and email_confirmed_at is not null) then
      raise exception using errcode='PT401',message='Войдите в аккаунт с подтверждённой почтой.';
    end if;
    if v_op not in ('bookmarks','setBookmark') then
      select role into v_role from knowledge_private.test_creators where user_id=v_uid for share;
      if v_role is null or v_role not in ('owner','deputy') then
        raise exception using errcode='PT403',message='Объявлениями и ссылками управляют владелец и заместитель.';
      end if;
    end if;
  end if;

  if v_op='setBookmark' then
    v_document:=knowledge_private.text_field(payload->'document','Документ',1,40);
    v_article:=knowledge_private.text_field(payload->'article','Статья',1,40);
    if jsonb_typeof(payload->'saved') is distinct from 'boolean' then
      raise exception using errcode='PT400',message='Укажите действие с избранным.';
    end if;
    if not exists(select 1 from knowledge_private.law_article_refs where document_id=v_document and article_id=v_article) then
      raise exception using errcode='PT404',message='Статья не найдена.';
    end if;
    if (payload->>'saved')::boolean then
      insert into knowledge_private.law_bookmarks(user_id,document_id,article_id) values(v_uid,v_document,v_article) on conflict do nothing;
    else
      delete from knowledge_private.law_bookmarks where user_id=v_uid and document_id=v_document and article_id=v_article;
    end if;
  end if;
  if v_op in ('bookmarks','setBookmark') then
    return jsonb_build_object('bookmarks',coalesce((select jsonb_agg(jsonb_build_object('document',document_id,'article',article_id) order by created_at desc,document_id,article_id) from knowledge_private.law_bookmarks where user_id=v_uid),'[]'::jsonb));
  end if;

  if v_op='saveAnnouncement' then
    v_title:=knowledge_private.text_field(payload->'title','Заголовок',3,140);
    v_body:=knowledge_private.text_field(payload->'body','Текст',1,6000);
    v_kind:=knowledge_private.text_field(payload->'kind','Тип объявления',1,20);
    if v_kind not in ('news','rules','attestation') then raise exception using errcode='PT400',message='Неизвестный тип объявления.'; end if;
    if jsonb_typeof(payload->'published') is distinct from 'boolean' or jsonb_typeof(payload->'pinned') is distinct from 'boolean' then
      raise exception using errcode='PT400',message='Укажите состояние публикации.';
    end if;
    v_published:=(payload->>'published')::boolean; v_pinned:=(payload->>'pinned')::boolean;
    v_event:=nullif(payload->>'eventAt','')::timestamptz;
    if v_event is not null and (not isfinite(v_event) or v_event<'2000-01-01'::timestamptz or v_event>'2200-01-01'::timestamptz) then
      raise exception using errcode='PT400',message='Проверьте дату события.';
    end if;
    v_id:=nullif(payload->>'id','')::uuid;
    if v_id is null then
      insert into knowledge_private.announcements(title,body,kind,event_at,pinned,published,published_at)
      values(v_title,v_body,v_kind,v_event,v_pinned,v_published,case when v_published then now() end) returning * into v_announcement;
    else
      v_version:=(payload->>'version')::integer;
      update knowledge_private.announcements set title=v_title,body=v_body,kind=v_kind,event_at=v_event,pinned=v_pinned,published=v_published,
        published_at=case when v_published then coalesce(published_at,now()) else published_at end,updated_at=now(),version=version+1
        where id=v_id and version=v_version returning * into v_announcement;
      if not found then raise exception using errcode='PT409',message='Объявление уже изменено. Обновите список и откройте его заново.'; end if;
    end if;
    return jsonb_build_object('id',v_announcement.id,'version',v_announcement.version);
  end if;
  if v_op in ('announcements','manageAnnouncements') then
    return jsonb_build_object('announcements',coalesce((select jsonb_agg(jsonb_build_object(
      'id',id,'title',title,'body',body,'kind',kind,'eventAt',event_at,'pinned',pinned,'published',published,
      'publishedAt',published_at,'updatedAt',updated_at,'version',version) order by pinned desc,coalesce(published_at,updated_at) desc,id)
      from knowledge_private.announcements where published or v_op='manageAnnouncements'),'[]'::jsonb));
  end if;

  if v_op='saveLink' then
    v_title:=knowledge_private.text_field(payload->'title','Название',3,120);
    v_description:=knowledge_private.text_field(coalesce(payload->'description','""'::jsonb),'Описание',0,300);
    v_url:=knowledge_private.text_field(payload->'url','Адрес',8,1500);
    if v_url !~ '^https://[A-Za-z0-9.-]+\.[A-Za-z]{2,}(:[0-9]{1,5})?([/?#][^[:space:]<>]*)?$' or (regexp_match(v_url,'^https://[^/?#]+:([0-9]+)'))[1]::integer not between 1 and 65535 then
      raise exception using errcode='PT400',message='Укажите полный адрес HTTPS без логина и пароля в ссылке.';
    end if;
    v_category:=knowledge_private.text_field(payload->'category','Раздел',1,20);
    if v_category not in ('forum','appeals','reports','contact') then raise exception using errcode='PT400',message='Неизвестный раздел ссылок.'; end if;
    if jsonb_typeof(payload->'published') is distinct from 'boolean' then raise exception using errcode='PT400',message='Укажите состояние публикации.'; end if;
    v_published:=(payload->>'published')::boolean;
    if coalesce(payload->>'position','') !~ '^[0-9]{1,4}$' then raise exception using errcode='PT400',message='Порядок: число от 0 до 1000.'; end if;
    v_position:=(payload->>'position')::integer;
    if v_position>1000 then raise exception using errcode='PT400',message='Порядок: число от 0 до 1000.'; end if;
    v_id:=nullif(payload->>'id','')::uuid;
    if v_id is null then
      insert into knowledge_private.useful_links(title,description,url,category,position,published)
      values(v_title,v_description,v_url,v_category,v_position,v_published) returning * into v_link;
    else
      v_version:=(payload->>'version')::integer;
      update knowledge_private.useful_links set title=v_title,description=v_description,url=v_url,category=v_category,position=v_position,
        published=v_published,updated_at=now(),version=version+1 where id=v_id and version=v_version returning * into v_link;
      if not found then raise exception using errcode='PT409',message='Ссылка уже изменена. Обновите список и откройте её заново.'; end if;
    end if;
    return jsonb_build_object('id',v_link.id,'version',v_link.version);
  end if;
  if v_op in ('links','manageLinks') then
    return jsonb_build_object('links',coalesce((select jsonb_agg(jsonb_build_object(
      'id',id,'title',title,'description',description,'url',url,'category',category,'position',position,'published',published,'version',version)
      order by position,title,id) from knowledge_private.useful_links where published or v_op='manageLinks'),'[]'::jsonb));
  end if;
  raise exception using errcode='PT400',message='Неизвестная операция.';
exception when invalid_text_representation or invalid_datetime_format or datetime_field_overflow or numeric_value_out_of_range then
  raise exception using errcode='PT400',message='Проверьте данные формы.';
end;
$$;
revoke all on function knowledge_private.portal(jsonb) from public,anon,authenticated;
grant usage on schema knowledge_private to anon;
grant execute on function knowledge_private.portal(jsonb) to anon,authenticated;
create function public.knowledge_portal(payload jsonb default '{}'::jsonb)
returns jsonb language sql security invoker set search_path='' as $$ select knowledge_private.portal(payload); $$;
revoke all on function public.knowledge_portal(jsonb) from public,anon,authenticated;
grant execute on function public.knowledge_portal(jsonb) to anon,authenticated;
comment on function public.knowledge_portal(jsonb) is 'Only published announcements/links are public. Bookmarks require a confirmed auth.uid(); editorial writes require the live owner/deputy role.';
